name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: make setup
      - run: make build
      - run: make encrypt-fake-competition
      - run: make check-package.json
      - run: make clean

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: make setup
      - run: make lint
      - run: make clean
